### ISSUE TITLE
App Login

### ISSUE THREAD

**Issue by sharmajiji** [espressif/esp-rainmaker-android#35] opened 2023-02-25 10:38 UTC
In esp rainmaker app login is not working i have tried from several devices and mail ids to login but it show failed to login.

**Comment by shahpiyushv** [comment] 2023-02-28 19:06
There were some certificate issues with the app which were fixed in version 2.10.1. Account creation/login has no relation to bluetooth. Probably things worked on the tablet because it may have downloaded the latest app.

**Comment by FernandoGarcia** [comment] 2023-02-28 22:52
Makes sense. Thanks!

**Comment by khushbushah2302** [comment] 2023-03-25 07:05
Hi @sharmajiji , the issue is fixed in latest 2.10.1 version app.

**Closed** 2023-03-25 16:50 UTC
